### ISSUE TITLE
I cannot use in dynamic route when I refresh page it's error

### ISSUE THREAD

**Issue by lagmanzaza** [davidroyer/nuxt-ssr-firebase#4]

**Comment by davidroyer** [comment]
Everything has been updated so everything should work now

**Comment by Nayir** [comment]
Hello @davidroyer, I still have the same problem when I'm trying to refresh a route different from the root. For example my example.com/login is not rendering when I try to refresh the page. Do you all have the same issue ?
